a =input("Nhap a")
#print(type(a))
a=int(a)

b = input("nhap b")
#print(type(b))
b= int(b)
print("{0}+{1}={2}".format(a,b,a+b))
print("{0}-{1}={2}".format(a,b,a-b))
print("{0}*{1}={2}".format(a,b,a*b))
print("{0}/{1}={2}".format(a,b,a/b))
print("{0}%{1}={2}".format(a,b,a%b))
print("{0}**{1}={2}".format(a,b,a**b))
print("{0}//{1}={2}".format(a,b,a//b))

